### ISSUE TITLE
Add Drupal Entity support

### ISSUE THREAD

**Issue by AnnaGerber** [uq-eresearch/austese_repository#28]
So that entities e.g. Agents, Works, Versions etc can be assigned owners, permissions and be part of workflows within drupal and so that we can get rid of the dependency on the slim framework (use drupal CRUD instead)

**Comment by omad** [comment]
This turned out to be infeasible. All of the metadata records are stored in MongoDB, and are accessed from client side javascript. Changing them to be drupal entities would require massive restructuring and re-writing.

As a compromise, the REST API the client accesses was converted to use drupal APIs. This lets the drupal permission system be used.
